name: Build Android Kotlin Project
on:
  push:
    tags:
      - '*'
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: gradle/gradle-build-action@v2

      - name: Decode keystore
        run: echo "${{ secrets.MC_KEYSTORE }}" | base64 --decode > app/mc.jks

      - name: Build release apk
        run: ./gradlew assembleRelease
        env:
          MC_SIGNING_KEY_ALIAS: ${{ secrets.MC_SIGNING_KEY_ALIAS }}
          MC_SIGNING_KEY_PASSWORD: ${{ secrets.MC_SIGNING_KEY_PASSWORD }}
          MC_SIGNING_STORE_PASSWORD: ${{ secrets.MC_SIGNING_STORE_PASSWORD }}

      - name: Find APK path
        id: apk_path
        run: |
          APK_PATH=$(find $PWD -type f -name "*.apk" | grep release | head -n 1)
          echo "apk_path=${APK_PATH}" >> $GITHUB_OUTPUT

      - name: Create Release and Upload APK
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ steps.apk_path.outputs.apk_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.MC_RELEASE }}